on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Upload public folder
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: server239.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          exclude: index.php
          server-dir: /myplanapi.betaapps.dev/

      - name: 📂 Upload project files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: server239.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: public/
          server-dir: /myplanapi/
