on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies and optimize
        run: |
          composer install --no-ansi --no-interaction --no-progress --prefer-dist
          php artisan config:cache
          php artisan config:clear
          php artisan cache:clear
        env: 
          APP_ENV: production
          APP_URL: ${{ secrets.PRODUCTION_URL }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Upload project files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: server239.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: public/
          server-dir: ${{ secrets.APP_FOLDER_PATH }}

      - name: Upload public folder
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: server239.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          exclude: index.php
          server-dir: ${{ secrets.APP_PUBLIC_FOLDER_PATH }}
